#ifndef ESPANNOL__H
#define ESPANNOL__H

#define MSJ_MENU_BIENVENIDO "Bienvenido/a"
#define MSJ_MENU_OPCIONES "Por favor, elija una opción"
#define MSJ_MENU_MOD_REGISTRO "Modificar registro personal"
#define MSJ_MENU_MOD_ASIG "Modificar asignatura"
#define MSJ_MENU_FINALIZAR "Finalizar"
#define MSJ_MENU_VOLVER "Volver"
#define MSJ_MENU_SALIR "Salir"
#define MSJ_MENU_REG_NOMBRE "Nombre"
#define MSJ_MENU_REG_PADRON "Padrón"
#define MSJ_MENU_REG_CARRERA "Carrera"
#define MSJ_NUEVA_ASIG "Ingresar nueva asignatura"
#define MSJ_DESPEDIDA "Hasta luego "
#define MSJ_ERROR "Error"
#define MSJ_OPCION_INVALIDA "Opción no válida"
#define MSJ_PUNTERO_NULO "Puntero nulo"
#define MSJ_MOD_NOMBRE "Ingrese nombre y apellido"
#define MSJ_MOD_PADRON "Ingrese su padrón"
#define MSJ_MOD_CARRERA "Ingrese el código de la carrera"
#define MSJ_INGRESO_ASIG "Por favor, ingrese su asignatura"
#define MSJ_INGRESO_NOTA "Por favor, ingrese su nota"
#define MSJ_REINTENTO "Por favor, intente nuevamente"
#define MSJ_MENU_METRICA "Métrica"
#define MSJ_MENU_METRICA_PROMEDIO "Promedio"
#define MSJ_MENU_METRICA_MAXIMO "Máximo"
#define MSJ_MENU_METRICA_MINIMO "Mínimo"
#define MSJ_MENU_METRICA_CANT_ASIG "Cantidad de asignaturas"
#define MSJ_MENU_METRICA_APLAZOS "Aplazos"
#define MSJ_ELECTRONICA "Ing. Electrónica"
#define MSJ_QUIMICA "Ing. Química"
#define MSJ_ALIMENTOS "Ing. en Alimentos"
#define MSJ_INDUSTRIAL "Ing. Industrial"
#define MSJ_MECANICA "Ing. Mecánica"
#define MSJ_ASIG_VACIA "No tiene ninguna asignatura cargada"
#define MSJ_ASIG_CARGADAS "Asignaturas cargadas:"
#define MSJ_NO_DATA "No hay datos ingresados"

#endif