#ifndef INGLES__H
#define INGLES__H

#define MSJ_MENU_BIENVENIDO "Welcome"
#define MSJ_MENU_OPCIONES "Please,choose an option"
#define MSJ_MENU_MOD_REGISTRO "Modificate personal register"
#define MSJ_MENU_MOD_ASIG "Modificate subject"
#define MSJ_MENU_FINALIZAR "End"
#define MSJ_MENU_VOLVER "Return"
#define MSJ_MENU_SALIR "Exit"
#define MSJ_MENU_REG_NOMBRE "Name"
#define MSJ_MENU_REG_PADRON "ID"
#define MSJ_MENU_REG_CARRERA "Career"
#define MSJ_NUEVA_ASIG "Enter a subject"
#define MSJ_DESPEDIDA "Bye "
#define MSJ_ERROR "Error"
#define MSJ_OPCION_INVALIDA "Invalid option"
#define MSJ_PUNTERO_NULO "Null pointer"
#define MSJ_MOD_NOMBRE "Enter name and lastname"
#define MSJ_MOD_PADRON "Enter your ID"
#define MSJ_MOD_CARRERA "Enter career's code"
#define MSJ_INGRESO_ASIG "Please, enter assigment"
#define MSJ_INGRESO_NOTA "Please, enter your note"
#define MSJ_MENU_METRICA "Metrics"
#define MSJ_MENU_METRICA_PROMEDIO "Average"
#define MSJ_MENU_METRICA_MAXIMO "Maximum"
#define MSJ_MENU_METRICA_MINIMO "Minimum"
#define MSJ_MENU_METRICA_CANT_ASIG "Number of assigments"
#define MSJ_ELECTRONICA "Electronic Engineering"
#define MSJ_QUIMICA "Chemical Engineering"
#define MSJ_ALIMENTOS "Food Engineering"
#define MSJ_INDUSTRIAL "Industrial Engineering"
#define MSJ_MECANICA "Mechanical Engineering"
#define MSJ_ASIG_VACIA "No subject loaded"
#define MSJ_ASIG_CARGADAS "Subjects loaded"
#define MSJ_NO_DATA "No data loaded"

#endif
